export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const COMPLETE_ALL = 'COMPLETE_ALL'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const MOVE_TODO = 'MOVE_TODO'
export const  ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REMOVE_TODO = 'REMOVE_TODO';
export const LOAD_TODOS = 'LOAD_TODOS';
export const DRAG_END= 'DRAG_END';
export const MOVE_POS = 'MOVE_POS';
export const CREATE_BOARD_TITLE = 'CREATE_BOARD_TITLE';
export const UPDATE_BOARD_TITLE = 'UPDATE_BOARD_TITLE';
export const GET_BOARD_TITLES = "GET_BOARD_TITLES";
